/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as AskThreadIdRouteImport } from './routes/ask.$threadId'
import { Route as TopicTopicIdRouteImport } from './routes/topic.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskThreadIdRoute = AskThreadIdRouteImport.update({
  id: '/ask/$threadId',
  path: '/ask/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/ask/': typeof AskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/ask': typeof AskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/ask/': typeof AskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/ask/$threadId' | '/topic/$topicId' | '/ask/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/ask/$threadId' | '/topic/$topicId' | '/ask'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/ask/$threadId'
    | '/topic/$topicId'
    | '/ask/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  AskThreadIdRoute: typeof AskThreadIdRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
  AskIndexRoute: typeof AskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$threadId': {
      id: '/ask/$threadId'
      path: '/ask/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AskThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  AskThreadIdRoute: AskThreadIdRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
  AskIndexRoute: AskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
